title: Long Haul
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

blog_url: "https://momento1.github.io"
url: ""
baseurl: ""
paginate_path: "blog/page:num/"
# permalink: blog/:title/

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Home
    url: /index.html
  - title: About
    url: /about
  # - title: Contact
  #   url: /contact

social:
  github_url: https://github.com/
  github: momento1/momento1.github.io
  twitter: nikeed
  facebook: nikeed
  email: dkdmfpel@gmail.com

google_analytics: "UA-58263416-1"

comments: true
